apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: microservice-a-route
  namespace: serviceA
spec:
  parentRefs:
    - name: main-gateway
      namespace: monitoring
  hostnames:
    - "microservice-a.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: microservice-a
          port: 80

